name: Publish docker image to registry and test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish Docker image
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: webkeyfinder
        image-tag: latest

  run-and-test:
    needs: build-and-publish
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - run: docker pull ghcr.io/dogayuksel/webkeyfinder/webkeyfinder:latest
      - run: docker run -d -p 3000:3000 ghcr.io/dogayuksel/webkeyfinder/webkeyfinder:latest
      - name: Cypress run
        uses: cypress-io/github-action@v2
